# Generated by Django 5.2 on 2025-05-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.IntegerField(choices=[(0, 'Paperback'), (1, 'Hardcover'), (2, 'Kindle')], default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
